### ISSUE TITLE
3rd Party Integrations

### ISSUE THREAD

**Issue by davidjeba** [What-the-Flutter/Suggest-a-Feature#69]
Hi,

Can this be integrated into 3rd party tools like canny.io, productboard.com etc

so that devs can actively work in an elaborate feedback backend.

**Comment by KirillSergeevich** [comment]
Hello @davidjeba 
There is `SuggestionsDataSource`, and you can implement as you want. 
Also we created a [package](https://pub.dev/packages/suggest_a_feature_firestore) for Firestore. You can check its implementation and create your own datasource.

**Comment by davidjeba** [comment]
https://developers.canny.io/api-reference#intro is the API for Canny.io
Can you help how it can be integrated, ill try it

**Comment by alesiaradkevich** [comment]
You can create a class that extends `SuggestionDataSource` in your project and implement its methods to integrate with canny.io. For example:

- You can send `POST` request in `createSuggestion(CreateSuggestionModel suggestion)` method to create suggestion (post) on `canny.io`
- To get all suggestions or one specific suggestion you can send request to `canny.io` in `getAllSuggestions()` or `getSuggestionById(String suggestionId)` methods accordingly
- To update suggestion (post) you can send request to `canny.io` in `updateSuggestion(Suggestion suggestion)` method
- To delete suggestion(post) you can send request to `canny.io` in `deleteSuggestionById(String suggestionId)` method
- To create comment for suggestion(post) you can send request to `canny.io` in `createComment(CreateCommentModel comment)`
- To delete comment you can send request to `canny.io` in `deleteCommentBuId(String commentId)` method
- To get all comments for suggestion(post) you can send request to `canny.io` in `getAllComments(String suggestionId)` method
- To add vote to the suggestion(post) you can send request to `canny.io` in `vote(String suggestionId)` method
- To delete vote from suggestion(post) you can send request to `canny.io` in `downvote(String suggestionId)`
- To subscribe the user to the status changes of the suggestion(post) you can send request to `canny.io` in `addNotifyToUpdateUser(String suggestionId)`
- To unsubscribe the user from the status changes of the suggestion(post) you can send request to `canny.io` in `deleteNotifyToUpdateUser(String suggestionId)` method

Hope this helps
